//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntercambioDeIdiomas
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENSAJES
    {
        public int IdMensaje { get; set; }
        public string Asunto { get; set; }
        public string CuerpoMensaje { get; set; }
        public int IdMensajePadre { get; set; }
        public bool Visto { get; set; }
        public string EmailReceptor { get; set; }
        public string EmailEmisor { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaVisto { get; set; }
    }
}
