//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntercambioDeIdiomas
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCIA
    {
        public int codigo_provincia { get; set; }
        public Nullable<int> com_autonoma_id { get; set; }
        public string provincia1 { get; set; }
    }
}
