//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntercambioDeIdiomas
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string email { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string intereses { get; set; }
        public int edad { get; set; }
        public Nullable<int> idioma_nativo { get; set; }
        public Nullable<int> idioma_que_estudia { get; set; }
        public string CIUDAD { get; set; }
        public string GENERO { get; set; }
        public string nivel_idioma_que_estudia { get; set; }
        public string path_imagen_perfil { get; set; }
    
        public virtual LENGUAJES LENGUAJES { get; set; }
        public virtual LENGUAJES LENGUAJES1 { get; set; }
        public virtual CIUDADES CIUDADES { get; set; }
    }
}
